name: Build and Publish Web Site

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Install pnpm
        run: |
          curl -fsSL https://get.pnpm.io/v6.16.js | node - add --global pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.vercel/output/static
          cname: sbc.om
